apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phoenix-ingress
  namespace: portfoliov4
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Turn off SSL redirection since no certificate is used
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: phoenix-service
            port:
              number: 80
