apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-app
  namespace: portfoliov4
  labels:
    app: phoenix-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phoenix-app
  template:
    metadata:
      labels:
        app: phoenix-app
    spec:
      containers:
        - name: phoenix-container
          image: ghcr.io/danielbutlerismyname/portfoliov4:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: "ecto://postgres:postgres@postgres:5432/portfoliov4_prod"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: phoenix-secrets
                  key: secret_key_base
            - name: PHX_HOST
              value: "37.156.41.23"
            - name: PORT
              value: "4000"
          # Uncomment and adjust the liveness/readiness probes as needed:
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 4000
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 4000
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: phoenix-service
spec:
  selector:
    app: phoenix-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
