apiVersion: v1
kind: Secret
metadata:
  name: phoenix-secrets
type: Opaque
stringData:
  secret_key_base: "QKdqV7HSTcVQzwOu7sl9v3CIvpCLDQdaSc5TzJGccNL13ABGUIsRLkyOiSzSN9gu"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  password: "postgres"
