name: build-push-image

on:
  workflow_run:
    workflows: ["build-test-elixir"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            --tag portfoliov4:${{ github.sha }} \
            --tag portfoliov4:latest
